export const reactionEmoji: Record<string, string> = {
  heart: '❤️',
  laugh: '😂',
  wow: '😮',
  sad: '😢',
  celebrate: '🎉',
  like: '👍',
  dislike: '👎',
  angry: '😡',
  love: '🥰',
  fire: '🔥',
  clap: '👏',
  thanks: '🙏',
  party: '🥳',
  thinking: '🤔',
  support: '💪',
  rocket: '🚀',
  eyes: '👀',
  sparkles: '✨',
  smile: '😊',
  wink: '😉',
  kiss: '😘',
  confused: '😕',
  cry: '😭',
  poop: '💩',
};
